# image will be published to ghcr.io/<user>/<name>
name: ublue-sysimage
# description will be included in the image's metadata
description: These are my personal OS images.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-39/tofik-nwg-shell-fedora-39.repo
        #     - https://copr.fedorainfracloud.org/coprs/eddsalkield/swaylock-effects/repo/fedora-39/eddsalkield-swaylock-effects-fedora-39.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-39/solopasha-hyprland-fedora-39.repo
    install:
      - curl
      - git
      - hyprland-git
      - hyprland-contrib
      - hyprland-plugins-git
      - hyprpaper
      - hyprpicker
      - hyrpidle
      - hyprshot
      - nwg-clipman
      - cliphist
      - aylurs-gtk-shell
      - swww
      - waypaper
      - hyprnome
      - hyprdim
      - swaylock-effects
      - waybar-git
      - xdg-desktop-portal-hyprland
      - grim
      - gvfs
      - gvfs-mtp
      - ImageMagick
      - jq
      - kitty
      - kvantum
      - nano
      - network-manager-applet
      - openssl
      - pamixer
      - pavucontrol
      - pipewire-alsa
      - playerctl
      - polkit-gnome
      - python3-requests
      - foot
      - thunar
      - nautilus
      - kate
      - nwg-shell
      - python3-pip
      - qt5ct
      - qt6ct
      - qt6-qtsvg
      - rofi-wayland
      - slurp
      - swappy
      - swayidle
      - SwayNotificationCenter
      - waybar
      - wget
      - wl-clipboard  	
      - wlogout
      - xdg-user-dirs
      - xdg-utils  	
      - yad
      - brightnessctl
      - btop
      - cava
      - eog
      - gnome-system-monitor
      - mousepad
      - mpv  	
      - mpv-mpris
      - neovim
        #      - cliphist
      - pamixer
      - swaylock
      - swaylock-effects
        #- swww
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
        # only normal flatpak applications are (like Floorp Lightning web browser in this example).
        # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
